#!/bin/bash

docker run                                                       \
 	--rm                                                         \
 	-v /tmp/.X11-unix:/tmp/.X11-unix                             \
 	-v .:/app/ -v nvim_data:/root/.local/share/nvim/             \
 	-v nvim_state:/root/.local/state/nvim/                       \
 	-v $HOME/.config/dockIDE/:/root/.config/nvim/                \
 	-v $(dirname $SSH_AUTH_SOCK) -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK \
 	-v $HOME/.ssh:/root/.ssh:ro                                  \
 	-e DISPLAY                                                   \
 	-e XAUTHORITY                                                \
 	-e QT_X11_NO_MITSHM=1                                        \
	--env-file $HOME/.config/dockIDE/user.env                    \
	trantorian/nvim:0.9 > output.log 2>&1 &
