#!/bin/bash

docker run -it                                       \
	-v .:/app/ -v nvim_data:/root/.local/share/nvim/ \
	-v nvim_state:/root/.local/state/nvim/           \
	-v $HOME/.config/dockIDE/:/root/.config/nvim/    \
	-v $SSH_AUTH_SOCK:/ssh-agent                     \
	-e $HOME/.config/dockIDE/user.env                \
	trantorian/nvim:0.2
