version: '3'

services:
  nvim:
    build: .
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    env_file:
      - user.env
    volumes:
      - ./nvim/:/root/.config/nvim
      - .:/app/
      - $SSH_AUTH_SOCK:/ssh-agent
      - lazy_data:/root/.local/share/nvim/
      - lazy_state:/root/.local/state/nvim/

volumes:
  lazy_data:
  lazy_state:
