#!/bin/bash

docker run --rm -it                                  \
	-v .:/app/ -v nvim_data:/root/.local/share/nvim/ \
	-v nvim_state:/root/.local/state/nvim/           \
	-v $HOME/.config/dockIDE/:/root/.config/nvim/    \
	-v $(dirname $SSH_AUTH_SOCK) -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK \
	-v $HOME/.ssh:/root/.ssh:ro \
	--env-file $HOME/.config/dockIDE/user.env                \
	trantorian/nvim:0.6
